# Generated by Django 3.2.10 on 2021-12-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('ID_Imovel', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('imagem1', models.ImageField(upload_to='img_imoveis/%y')),
            ],
        ),
    ]
