# Generated by Django 3.2.10 on 2021-12-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='area',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='banheiro',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='imagem2',
            field=models.ImageField(default=1, upload_to='img_imoveis/%y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='imagem3',
            field=models.ImageField(default=1, upload_to='img_imoveis/%y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='informacao',
            field=models.TextField(default=1, help_text='Descrição', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
