# Generated by Django 3.2.10 on 2021-12-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211213_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='categoria',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
