# Generated by Django 3.2.10 on 2021-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_imovel_imagem4'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='Tipo',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Terreno', 'Terreno')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
