# Generated by Django 3.2.10 on 2021-12-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_tipo_imovel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='valor',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
