# Generated by Django 3.2.10 on 2021-12-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_imovel_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='imageDep',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem1',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem2',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem3',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem4',
            field=models.URLField(max_length=300),
        ),
    ]
